package by.bsuir.computershop.dao.entity;
// Generated Feb 12, 2013 8:53:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personalcomputer generated by hbm2java
 */
public class Personalcomputer  implements java.io.Serializable {


     private int idPersonalComputer;
     private Type type;
     private String namePc;
     private Date releaseDate;
     private String platform;
     private String processor;
     private int numberOfCores;
     private float weight;
     private float diagonal;
     private int operationMemory;
     private int hardDisk;
     private float price;
     private Float discount;
     private Set<Purchase> purchases = new HashSet<Purchase>(0);

    public Personalcomputer() {
    }

	
    public Personalcomputer(int idPersonalComputer, Type type, String namePc, Date releaseDate, String platform, String processor, int numberOfCores, float weight, float diagonal, int operationMemory, int hardDisk, float price) {
        this.idPersonalComputer = idPersonalComputer;
        this.type = type;
        this.namePc = namePc;
        this.releaseDate = releaseDate;
        this.platform = platform;
        this.processor = processor;
        this.numberOfCores = numberOfCores;
        this.weight = weight;
        this.diagonal = diagonal;
        this.operationMemory = operationMemory;
        this.hardDisk = hardDisk;
        this.price = price;
    }
    public Personalcomputer(int idPersonalComputer, Type type, String namePc, Date releaseDate, String platform, String processor, int numberOfCores, float weight, float diagonal, int operationMemory, int hardDisk, float price, Float discount, Set<Purchase> purchases) {
       this.idPersonalComputer = idPersonalComputer;
       this.type = type;
       this.namePc = namePc;
       this.releaseDate = releaseDate;
       this.platform = platform;
       this.processor = processor;
       this.numberOfCores = numberOfCores;
       this.weight = weight;
       this.diagonal = diagonal;
       this.operationMemory = operationMemory;
       this.hardDisk = hardDisk;
       this.price = price;
       this.discount = discount;
       this.purchases = purchases;
    }
   
    public int getIdPersonalComputer() {
        return this.idPersonalComputer;
    }
    
    public void setIdPersonalComputer(int idPersonalComputer) {
        this.idPersonalComputer = idPersonalComputer;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public String getNamePc() {
        return this.namePc;
    }
    
    public void setNamePc(String namePc) {
        this.namePc = namePc;
    }
    public Date getReleaseDate() {
        return this.releaseDate;
    }
    
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }
    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    public String getProcessor() {
        return this.processor;
    }
    
    public void setProcessor(String processor) {
        this.processor = processor;
    }
    public int getNumberOfCores() {
        return this.numberOfCores;
    }
    
    public void setNumberOfCores(int numberOfCores) {
        this.numberOfCores = numberOfCores;
    }
    public float getWeight() {
        return this.weight;
    }
    
    public void setWeight(float weight) {
        this.weight = weight;
    }
    public float getDiagonal() {
        return this.diagonal;
    }
    
    public void setDiagonal(float diagonal) {
        this.diagonal = diagonal;
    }
    public int getOperationMemory() {
        return this.operationMemory;
    }
    
    public void setOperationMemory(int operationMemory) {
        this.operationMemory = operationMemory;
    }
    public int getHardDisk() {
        return this.hardDisk;
    }
    
    public void setHardDisk(int hardDisk) {
        this.hardDisk = hardDisk;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public Float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Float discount) {
        this.discount = discount;
    }
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }




}


