package by.bsuir.computershop.dao.entity;
// Generated Feb 12, 2013 8:53:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private int idType;
     private String nameType;
     private Set<Notebook> notebooks = new HashSet<Notebook>(0);
     private Set<Personalcomputer> personalcomputers = new HashSet<Personalcomputer>(0);

    public Type() {
    }

	
    public Type(int idType, String nameType) {
        this.idType = idType;
        this.nameType = nameType;
    }
    public Type(int idType, String nameType, Set<Notebook> notebooks, Set<Personalcomputer> personalcomputers) {
       this.idType = idType;
       this.nameType = nameType;
       this.notebooks = notebooks;
       this.personalcomputers = personalcomputers;
    }
   
    public int getIdType() {
        return this.idType;
    }
    
    public void setIdType(int idType) {
        this.idType = idType;
    }
    public String getNameType() {
        return this.nameType;
    }
    
    public void setNameType(String nameType) {
        this.nameType = nameType;
    }
    public Set<Notebook> getNotebooks() {
        return this.notebooks;
    }
    
    public void setNotebooks(Set<Notebook> notebooks) {
        this.notebooks = notebooks;
    }
    public Set<Personalcomputer> getPersonalcomputers() {
        return this.personalcomputers;
    }
    
    public void setPersonalcomputers(Set<Personalcomputer> personalcomputers) {
        this.personalcomputers = personalcomputers;
    }




}


